language: node_js
sudo: false

node_js:
  - "6"

branches:
  only:
    - master

services:
  - postgresql

before_script:
  - psql -c 'create database beam_test;' -U postgres

script: npm run build && npm run test
